const types =
{
    ARTICLE_REQUEST :"ARTICLE_REQUEST",
    ARTICLE_SUCCESS :"ARTICLE_SUCCESS",
    ARTICLE_FAILURE :"ARTICLE_FAILURE",

    UPDATE_ARTICLE_REQUEST :"UPDATE_ARTICLE_REQUEST",
    UPDATE_ARTICLE_SUCCESS :"UPDATE_ARTICLE_SUCCESS",
    UPDATE_ARTICLE_FAILURE :"UPDATE_ARTICLE_FAILURE",
}

export default types;