const types = {
    BLOG_LIST_REQUEST :"BLOG_LIST_REQUEST",
    BLOG_LIST_SUCCESS :"BLOG_LIST_SUCCESS",
    BLOG_LIST_FAILURE :"BLOG_LIST_FAILURE",

    ADD_BLOG_REQUEST :"ADD_BLOG_REQUEST",
    ADD_BLOG_SUCCESS :"ADD_BLOG_SUCCESS",
    ADD_BLOG_FAILURE :"ADD_BLOG_FAILURE",
}

export default types;